Add popup (feedback) form in contact component
1gory/case-shop pull request #15
Opened 2017-07-19 11:10 UTC by bahoss

2017-07-19 16:22 UTC, 1gory requested changes
Вообще неплохо! Hо:
1) этот popup должен быть с positon: absolute 
2) за ним должен быть темный полупрозрачный фон, закрыавющий всю страницу

2017-07-19 16:22 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +    font-family: 'Lato-Regular';
color: #4a4a4a;

2017-07-19 16:22 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +    <StyledLink to='/'><img src={ModalClose}/></StyledLink>
Это не Link, стилизуй img
Оберни с H3 в обертку и display flex

2017-07-19 16:22 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +import { Link } from 'react-router-dom';
1) ModalClose с маленькой буквы
2) Сначала идут импорты абсолютные, потом относительные

2017-07-19 16:22 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +  float: right;
float'ы не используем

2017-07-19 16:22 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +  float: left;
float'ы не используем

2017-07-19 16:22 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +  clear: both;
~~clear: both;~~

2017-07-19 16:22 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +    border-radius: 19px;
20px

2017-07-19 16:22 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +  & div {
ButtonWrapper

2017-07-19 16:22 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +  & button {
SendButton

2017-07-19 16:22 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +    padding: 12px 51px;
padding: 10px 50px;

2017-07-19 16:22 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +    border-radius: 19px;
20px

2017-07-19 16:22 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +  color: #b0b0b0;
ты же уже задал цвет в другом месте + тут не работет

2017-07-19 17:20 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +const H4 = styled.p`
H4 = p ???

2017-07-19 17:20 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +  margin-bottom: 9px;
10px

2017-07-23 11:35 UTC, 1gory requested changes
![image](https://user-images.githubusercontent.com/6150755/28498996-d062a6e2-6f9a-11e7-84aa-3cb6b45b6ded.png)
1) поп-ап вылазиет за границы сайта
2) за ним нет фона (фон должен быть на всей странице)
3) при просмотре с мобильного поп-ап прилипает к границам экрана

2017-07-23 11:35 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.jsx
> +import modalclose from './modal-close.svg';
Camel case

2017-07-23 11:35 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +        <InputMessage placeholder='Введите сообщение...' type='text' height='135'/>
height='135' ?

2017-07-23 11:35 UTC, 1gory commented on src/components/MainPage/Contacts/modal-close.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
Приведи контент к виду, как другие svg

2017-07-23 11:35 UTC, 1gory commented on src/components/MainPage/Contacts/index.jsx
> +    <FeedbackPopUp/>
Я не знаю почему линтер пропускает это, но тут должен быть пробел перед закрывающей чертой

2017-07-23 11:35 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +  height: 100vh;
Ты осмысленно это вставил? Сможешь объяснить зачем?

2017-07-23 11:44 UTC, bahoss commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +  height: 100vh;
это для того чтобы высота была равна размером экрана пользователя

2017-07-23 11:51 UTC, bahoss commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +        <InputMessage placeholder='Введите сообщение...' type='text' height='135'/>
это высота textarea

2017-07-23 12:03 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +        <InputMessage placeholder='Введите сообщение...' type='text' height='135'/>
А это у тебя что?
const InputMessage = styled.textarea`
  height: 125px;

2017-07-23 12:05 UTC, 1gory commented on src/components/MainPage/Contacts/FeedbackPopUp.js
> +  height: 100vh;
А, ну поэтому фон и вылезает за пределы сайта, как я показал на скрине.

2017-08-20 14:04 UTC, closed without merging