Add catalog page and three feedback forms
1gory/case-shop pull request #9
Opened 2017-07-15 12:15 UTC by bahoss

2017-07-15 12:29 UTC, 1gory requested changes

2017-07-15 12:29 UTC, 1gory commented on src/App.js
> +                  {/* Нужно написать и импортировать Catalog */}
Это удалить

2017-07-15 12:29 UTC, 1gory commented on src/App.js
> +import { BrowserRouter as Router, Route, Redirect, Switch } from 'react-router-dom';
Redirect лишний

2017-07-15 12:29 UTC, 1gory commented on src/components/Card/index.js
> +    cursor: pointer;
лишние отступы

2017-07-15 12:29 UTC, 1gory commented on src/components/Card/index.js
> +
лишний перенос

2017-07-15 12:29 UTC, 1gory commented on src/components/Catalog/index.js
> +  padding-bottom: 60px;
Это лишнее

2017-07-15 12:29 UTC, 1gory commented on src/components/Catalog/index.js
> +          <BreadCrumbs>
Не хватает надписи "Каталог гравированнх чехлов"

2017-07-15 12:29 UTC, 1gory commented on src/components/Catalog/index.js
> +        <Footer />
Тут не хватает карты и инфы о самовыозе, смотри макет

2017-07-15 12:29 UTC, 1gory commented on src/components/Catalog/index.js
> +        <Footer />
Ну и пагинации тоже нет

2017-07-15 12:31 UTC, 1gory commented on src/components/Catalog/index.js
> +        <Footer />
Кстати вынесы Map и SelfDelivery в Footer из MainPage

2017-07-15 12:32 UTC, bahoss commented on src/App.js
> +                  {/* Нужно написать и импортировать Catalog */}
что именно все эти 4 строки?

2017-07-15 12:33 UTC, 1gory commented on src/App.js
> +                  {/* Нужно написать и импортировать Catalog */}
Комментарий

2017-07-15 19:09 UTC, 1gory requested changes

2017-07-15 19:09 UTC, 1gory commented on src/components/Card/index.js
> +
По всему блоку что выше:
1) Лишние отступы (оставлял коммент в прошлый раз)
2) hover закомментируй (оставлял коммент в прошлый раз)
3) Лишний перенос между блоками

Не удаляй больше комментарии

2017-07-15 19:09 UTC, 1gory commented on src/components/Card/index.js
> +    cursor: pointer;
padding-bottom: 30px; 
потерял

2017-07-15 19:09 UTC, 1gory commented on src/components/Card/index.js
> +    cursor: pointer;
padding-top: 30px;
потерял

2017-07-15 19:09 UTC, 1gory commented on src/components/Catalog/index.js
> +`;
~~width: 38px;~~
~~height: 38px;~~
padding: 10px 15px;

2017-07-15 19:09 UTC, 1gory commented on src/components/Catalog/index.js
> +  border-radius: 20px;
~~width: 138px;~~
padding: 10px 20px;

2017-07-15 19:09 UTC, 1gory commented on src/components/Catalog/index.js
> +  margin :6px;
опечатка

2017-07-15 19:09 UTC, 1gory commented on src/components/Catalog/index.js
> +  opacity: 0.7;
Не используй opacity, если в маете не отображается нужный цвет, подбери по другим элементам, которые уже сверстаны

2017-07-15 19:09 UTC, 1gory commented on src/components/Catalog/index.js
> +  font-size: 32px;
сделай 24px, 32 много, это для десктопной версии

2017-07-15 19:09 UTC, 1gory commented on src/components/Catalog/index.js
> +  color: #4a4a4a;
Задай цвет для всего BreadCrumbs, иначе / - другого цвета

2017-07-15 19:09 UTC, 1gory commented on src/components/Catalog/index.js
> +  margin: 50px 0 0 50px;
~~line-height: 38px;~~
~~margin: 50px 0 0 50px;~~
padding: 50px;

2017-07-15 19:09 UTC, 1gory commented on src/components/Catalog/index.js
> +          <PagWrapper>
По-моему, неудачное сокращение, используй везде всесто Pag - Pagination

2017-07-15 19:14 UTC, 1gory commented on src/components/Catalog/index.js
> +      <Wrapper>
И заметь, цвета фона не совпадают

2017-07-16 05:54 UTC, bahoss commented on src/components/Card/index.js
> +
как hover за комментировать, коммент не могу найти...

2017-07-16 11:14 UTC, 1gory requested changes
Старые комментарии не исправлены

2017-07-16 11:14 UTC, 1gory commented on src/components/Catalog/index.js
> +  font-size: 28px;
Почему 28? я же написал 24

2017-07-16 11:14 UTC, 1gory commented on src/components/Catalog/index.js
> +  margin: 6px;
5px

2017-07-16 11:14 UTC, 1gory commented on src/components/Catalog/index.js
> +  text-align: left;
Убери отсюда 
text-align: left;

2017-07-16 11:14 UTC, 1gory commented on src/components/Catalog/index.js
> +  text-align: left;
Убери отсюда
text-align: left;

2017-07-16 11:14 UTC, 1gory commented on src/components/Catalog/index.js
> +  text-align: center;
Убери отсюда
text-align: center;

2017-07-16 11:14 UTC, 1gory commented on src/components/Card/index.js
> +  padding-bottom: 30px;
а вот сюда добавь text-align: center;

2017-07-16 16:46 UTC, 1gory requested changes
Не все комментарии поправлены

2017-07-17 08:21 UTC, 1gory requested changes
![image](https://user-images.githubusercontent.com/6150755/28260022-c241e96e-6ac8-11e7-9ed4-fafbe7854efc.png)

1) Нужно испрвить ошибки, возникающие при сборке
2) Нужно проставить ссылки на каталог в разных меню и на главной странице

2017-07-17 11:52 UTC, 1gory requested changes

2017-07-17 11:52 UTC, 1gory commented on src/components/MainPage/Catalog/index.js
> +}
Это куда???

2017-07-17 12:03 UTC, 1gory requested changes

2017-07-17 12:03 UTC, 1gory commented on src/components/MainPage/Catalog/index.js
>  import RubleSign from '../../RubleSign';
RubleSign не используется на странице

2017-07-17 12:18 UTC, 1gory approved these changes

2017-07-17 12:19 UTC, merged